Repository stolostron/discovery, pull requests merged in 2021-02, with the labels that each got.

#27 Update README.md
  README.md
  RELEASE_MAIN_BRANCH
Labels: approved, lgtm

#29 Add Dockerfile and Makefile for Prow jobs
  Dockerfile.prow
  Makefile.prow
Labels: approved, lgtm

#30 Short unit test target
  Makefile
  Makefile.prow
  controllers/suite_test.go
  integration_tests/controller_tests/suite_test.go
Labels: approved, lgtm

#31 Add cicd members as approvers/reviewers
  OWNERS
Labels: approved, lgtm

#32 Sonarcloud onboarding
  .travis.yml
  config/crd/bases/discovery.open-cluster-management.io_discoveredclusterrefreshes.yaml
  config/crd/bases/discovery.open-cluster-management.io_discoveredclusters.yaml
  config/crd/bases/discovery.open-cluster-management.io_discoveryconfigs.yaml
  config/rbac/role.yaml
  sonar-project.properties
  testserver/go.mod
Labels: approved, lgtm

#33 Sonar changes
  controllers/discoveryconfig_controller.go
  controllers/managedcluster_controller.go
  pkg/api/clients/restclient/authclient.go
  sonar-project.properties
  testserver/go.sum
  testserver/main.go
Labels: approved, kind/maintenance, lgtm

#35 Remove sonar and publish stages from Travis.
  .travis.yml
Labels: approved, lgtm

#36 Uncomment include in prow makefile
  Makefile.prow
Labels: approved, lgtm

#38 add eol to sonar-project.properties
  sonar-project.properties
Labels: approved, lgtm

#37 Update go version in readme
  README.md
Labels: approved

#40 Remove publish branch from Travis entirely
  .travis.yml
Labels: approved

#39 Add DCO and Contributing.md
  CONTRIBUTING.md
  DCO
  Makefile
Labels: approved, lgtm
