Repository stolostron/discovery, pull requests merged in 2021-03, with the labels that each got.

#41 Fit and finish open source
  Makefile
  README.md
  config/samples/kustomization.yaml
  config/samples/ocm-api-secret.yaml
Labels: approved, lgtm

#42 Update Makefile
  Makefile
Labels: approved, lgtm

#44 Add Architecture Diagram and Roadmap
  docs/ArchitectureDiagram.png
  docs/Roadmap.md
Labels: approved, lgtm

#45 Update README.md
  README.md
Labels: approved, lgtm

#46 Update README.md
  README.md
Labels: approved, lgtm

#47 Add OCM subscription api and filter archived clusters
  Makefile
  api/v1/zz_generated.deepcopy.go
  controllers/discoveryconfig_controller.go
  controllers/discoveryconfig_controller_test.go
  controllers/managedcluster_controller.go
  controllers/testdata/mock_clusters.json
  controllers/testdata/mock_clusters_2.json
  controllers/testdata/mock_subscriptions.json
  controllers/testdata/mock_subscriptions_2.json
  go.mod
  go.sum
  integration_tests/controller_tests/discoveryconfig_controller.go
  integration_tests/controller_tests/function_tests.go
  integration_tests/controller_tests/suite_test.go
  pkg/api/clients/restclient/subscriptionclient.go
  pkg/api/domain/subscription_domain/subscription_domain.go
  pkg/api/domain/subscription_domain/subscription_error.go
  pkg/api/providers/subscription_provider/subscription_provider.go
  pkg/api/providers/subscription_provider/subscription_provider_test.go
  pkg/api/providers/subscription_provider/testdata/accounts_mgmt_mock.json
  pkg/api/services/subscription_service/subscription_service.go
  pkg/api/services/subscription_service/subscription_service_test.go
  testserver/Makefile
  testserver/api/api.go
  testserver/api/auth.go
  testserver/api/clusters.go
  testserver/api/endpoints.go
  testserver/api/scenario.go
  testserver/api/subscriptions.go
  testserver/build/Dockerfile
  testserver/build/local-server/deploy.yaml
  testserver/build/local-server/kustomization.yaml
  testserver/data/clusters_list.json
  testserver/data/scenarios/archived_clusters/cluster_response.json
  testserver/data/scenarios/archived_clusters/subscription_response.json
  testserver/data/scenarios/five_clusters/cluster_response.json
  testserver/data/scenarios/five_clusters/subscription_response.json
  testserver/data/scenarios/ten_clusters/cluster_response.json
  testserver/data/scenarios/ten_clusters/subscription_response.json
  testserver/data/subscriptions.json
  testserver/go.mod
  testserver/go.sum
  testserver/main.go
Labels: approved, kind/user-story, lgtm

#48 Remove travis entirely
  .travis.yml
Labels: approved, lgtm

#49 Update README.md
  README.md
Labels: approved, lgtm

#50 Update README.md
  README.md
Labels: approved, lgtm

#51 Update README.md
  README.md
Labels: approved, lgtm

#53 Refactor managedcluster controller
  controllers/managedcluster_controller.go
  controllers/managedcluster_controller_test.go
Labels: approved, lgtm, refactor

#54 Enable running tests in KinD
  .gitignore
  Makefile
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  integration_tests/Makefile
  integration_tests/build/Dockerfile
  test/e2e/build/Dockerfile
  test/e2e/discoveryconfig_controller.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  testserver/Makefile
  testserver/build/local-server/kustomization.yaml
Labels: approved, lgtm

#56 Remove code for SonarCloud
  test/e2e/e2e.go
Labels: approved, lgtm

#58 Update go to v1.16. Cleanup dockerfiles.
  Dockerfile
  Dockerfile.prow
  Dockerfile.test.prow
  README.md
  go.mod
  test/e2e/build/Dockerfile
  testserver/build/Dockerfile
Labels: approved, lgtm

#59 Remove DiscoveredClusterRefresh from project
  PROJECT
  api/v1/discoveredclusterrefresh_types.go
  api/v1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/discovery.clusterserviceversion.yaml
  bundle/manifests/discovery.open-cluster-management.io_discoveredclusterrefreshes.yaml
  bundle/manifests/discovery.open-cluster-management.io_discoveredclusters.yaml
  bundle/manifests/discovery.open-cluster-management.io_discoveryconfigs.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/discovery.open-cluster-management.io_discoveredclusterrefreshes.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_discoveredclusterrefreshes.yaml
  config/crd/patches/webhook_in_discoveredclusterrefreshes.yaml
  config/manifests/bases/discovery.clusterserviceversion.yaml
  config/rbac/discoveredclusterrefresh_editor_role.yaml
  config/rbac/discoveredclusterrefresh_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/discovery_v1_discoveredclusterrefresh.yaml
  config/samples/kustomization.yaml
  controllers/discoveredclusterrefresh_controller.go
  main.go
  test/e2e/discoveryconfig_controller.go
Labels: approved, lgtm
